---
abstract: 'take a Benchmark and confirm returned values'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires: {}
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.53, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Benchmark-Confirm
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
provides:
  Benchmark::Confirm:
    file: lib/Benchmark/Confirm.pm
    version: 0.22
requires:
  Benchmark: 1.051
  Test::More: 0.88
  perl: v5.8.1
resources:
  bugtracker: https://github.com/bayashi/Benchmark-Confirm/issues
  homepage: https://github.com/bayashi/Benchmark-Confirm
  repository: git://github.com/bayashi/Benchmark-Confirm.git
version: 0.22
