---
abstract: 'take a Benchmark and confirm returned values'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Benchmark-Confirm
provides:
  Benchmark::Confirm:
    file: lib/Benchmark/Confirm.pm
    version: 0.03
requires:
  Benchmark: 1.051
  Test::More: 0.88
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Benchmark-Confirm
version: 0.03
